// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzfxyEuvyOpQo9nnpuzRVJH4Yma0HI-ck',
    appId: '1:405000031466:web:08a96552040311337f5b93',
    messagingSenderId: '405000031466',
    projectId: 'todo-app-6af42',
    authDomain: 'todo-app-6af42.firebaseapp.com',
    storageBucket: 'todo-app-6af42.appspot.com',
    measurementId: 'G-13KSJB9GGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAEKxWKt7x5tA7ucsgCwd671K28lb7-pPc',
    appId: '1:405000031466:android:14e758fba6c8b2977f5b93',
    messagingSenderId: '405000031466',
    projectId: 'todo-app-6af42',
    storageBucket: 'todo-app-6af42.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWpop6EK4RFiEzYYwaFn7hSak4dJfArQ8',
    appId: '1:405000031466:ios:303eb6de266f72757f5b93',
    messagingSenderId: '405000031466',
    projectId: 'todo-app-6af42',
    storageBucket: 'todo-app-6af42.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzfxyEuvyOpQo9nnpuzRVJH4Yma0HI-ck',
    appId: '1:405000031466:web:8328ef90ddeafcbe7f5b93',
    messagingSenderId: '405000031466',
    projectId: 'todo-app-6af42',
    authDomain: 'todo-app-6af42.firebaseapp.com',
    storageBucket: 'todo-app-6af42.appspot.com',
    measurementId: 'G-YXLZFXM9HC',
  );
}
